steps:
  # ── Build API ──
  - id: "build-api"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-api:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-api:latest"
      - "./api"

  # ── Build Web (monorepo — context from root) ──
  - id: "build-web"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "web/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-web:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-web:latest"
      - "--build-arg"
      - "NEXT_PUBLIC_API_URL=${_API_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "."
    waitFor: ["-"] # parallel with api build

  # ── Push Images ──
  - id: "push-api"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-api",
      ]
    waitFor: ["build-api"]

  - id: "push-web"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-web",
      ]
    waitFor: ["build-web"]

  # ── Deploy API to Cloud Run ──
  - id: "deploy-api"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gabi-api"
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-api:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=3"
      - "--port=8080"
      - "--allow-unauthenticated"
      - "--set-env-vars=GABI_GCP_PROJECT_ID=${PROJECT_ID},GABI_VERTEX_AI_LOCATION=${_REGION}"
      - "--set-secrets=GABI_DATABASE_URL=GABI_DATABASE_URL:latest,GABI_FIREBASE_ADMIN_SERVICE_ACCOUNT=GABI_FIREBASE_ADMIN_SA:latest"
      - '--set-env-vars=GABI_CORS_ORIGINS=["https://gabi.ness.com.br","https://gabi-web-${PROJECT_NUMBER}.run.app"]'
    waitFor: ["push-api"]

  # ── Deploy Web to Cloud Run ──
  - id: "deploy-web"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gabi-web"
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/gabi-web:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=3"
      - "--port=3000"
      - "--allow-unauthenticated"
    waitFor: ["push-web"]

substitutions:
  _REGION: us-central1
  _REPO: gabi
  _API_URL: https://gabi-api-CHANGEME.run.app
  _FIREBASE_API_KEY: ""
  _FIREBASE_AUTH_DOMAIN: ""
  _FIREBASE_PROJECT_ID: ""

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1200s
