global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']

  # Gabi services (when deployed)
  - job_name: 'gabi-os'
    static_configs:
      - targets: ['gabi-os:7777']
    metrics_path: '/metrics'

  - job_name: 'gabi-chat'
    static_configs:
      - targets: ['gabi-chat:3000']
    metrics_path: '/metrics'

  - job_name: 'gabi-ingest'
    static_configs:
      - targets: ['gabi-ingest:8000']
    metrics_path: '/metrics'
