version: "3.9"

# Gabi - Chat Multi-Agentes
# Ambiente Docker Desktop Local
# Organização: docker-desktop/gabi/

networks:
  gabi-network:
    driver: bridge
    name: gabi-network

volumes:
  gabi_postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
  gabi_redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
  gabi_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/uploads
  gabi_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/backups

services:
  # Banco de dados PostgreSQL + pgvector
  gabi-db:
    image: ankane/pgvector:latest
    container_name: gabi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gabi
      POSTGRES_PASSWORD: gabi_dev_secure_2024
      POSTGRES_DB: gabi_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - gabi_postgres_data:/var/lib/postgresql/data
      - ./config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - gabi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gabi -d gabi_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis para cache e sessões
  gabi-redis:
    image: redis:7-alpine
    container_name: gabi-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass gabi_redis_2024
    volumes:
      - gabi_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - gabi-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Traefik - Proxy reverso
  gabi-traefik:
    image: traefik:v2.11
    container_name: gabi-traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/traefik:/var/log/traefik
    networks:
      - gabi-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # gabi-os - AgentOS Runtime
  gabi-os:
    build:
      context: ../../../../
      dockerfile: dockerfiles/Dockerfile.gabi-os
    container_name: gabi-os
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://gabi:gabi_dev_secure_2024@db:5432/gabi_dev
      REDIS_URL: redis://:gabi_redis_2024@redis:6379/0
      OS_SECURITY_KEY: gabi_dev_security_key_2024
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-dev-openai-key-placeholder}
      AGNO_LOG_LEVEL: DEBUG
      AGNO_ENABLE_TELEMETRY: "false"
      PORT: 7777
    depends_on:
      gabi-db:
        condition: service_healthy
      gabi-redis:
        condition: service_healthy
    ports:
      - "7777:7777"
    volumes:
      - ./logs/gabi-os:/app/logs
      - gabi_uploads:/app/uploads
    networks:
      - gabi-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gabi-os.rule=Host(`localhost`) && PathPrefix(`/os`)"
      - "traefik.http.routers.gabi-os.entrypoints=web"
      - "traefik.http.services.gabi-os.loadbalancer.server.port=7777"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # gabi-chat - Interface Next.js
  gabi-chat:
    build:
      context: ../../../../
      dockerfile: dockerfiles/Dockerfile.gabi-chat
    container_name: gabi-chat
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_AGENTOS_URL: http://gabi-os:7777
      NEXT_PUBLIC_INGEST_URL: http://gabi-ingest:8000
      NODE_ENV: development
      PORT: 3000
    depends_on:
      gabi-os:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./logs/gabi-chat:/app/logs
      - gabi_uploads:/app/uploads
    networks:
      - gabi-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gabi-chat.rule=Host(`localhost`)"
      - "traefik.http.routers.gabi-chat.entrypoints=web"
      - "traefik.http.services.gabi-chat.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # gabi-ingest - Worker de processamento
  gabi-ingest:
    build:
      context: ../../../../
      dockerfile: dockerfiles/Dockerfile.gabi-ingest
    container_name: gabi-ingest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://gabi:gabi_dev_secure_2024@db:5432/gabi_dev
      REDIS_URL: redis://:gabi_redis_2024@redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-dev-openai-key-placeholder}
      PORT: 8000
    depends_on:
      gabi-db:
        condition: service_healthy
      gabi-redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./logs/gabi-ingest:/app/logs
      - gabi_uploads:/app/uploads
    networks:
      - gabi-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gabi-ingest.rule=Host(`localhost`) && PathPrefix(`/ingest`)"
      - "traefik.http.routers.gabi-ingest.entrypoints=web"
      - "traefik.http.services.gabi-ingest.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
