version: "3.9"

services:
  # Banco de dados PostgreSQL + pgvector
  gabi-db:
    image: ankane/pgvector:latest
    container_name: gabi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gabi
      POSTGRES_PASSWORD: gabi_dev_secure_2024
      POSTGRES_DB: gabi_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gabi -d gabi_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache e sessões
  gabi-redis:
    image: redis:7-alpine
    container_name: gabi-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass gabi_redis_2024
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Traefik - Proxy reverso
  gabi-traefik:
    image: traefik:v2.11
    container_name: gabi-traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"
    ports:
      - "8080:80"    # HTTP
      - "8081:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Aplicação de teste
  gabi-test:
    image: nginx:alpine
    container_name: gabi-test
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gabi-test.rule=Host(`localhost`)"
      - "traefik.http.routers.gabi-test.entrypoints=web"
      - "traefik.http.services.gabi-test.loadbalancer.server.port=80"
