name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NS: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          docker build -f dockerfiles/Dockerfile.gabi-os -t $REGISTRY/${IMAGE_NS}/gabi-os:latest .
          docker build -f dockerfiles/Dockerfile.gabi-chat -t $REGISTRY/${IMAGE_NS}/gabi-chat:latest .
          docker build -f dockerfiles/Dockerfile.gabi-ingest -t $REGISTRY/${IMAGE_NS}/gabi-ingest:latest .

      - name: Push images
        run: |
          docker push $REGISTRY/${IMAGE_NS}/gabi-os:latest
          docker push $REGISTRY/${IMAGE_NS}/gabi-chat:latest
          docker push $REGISTRY/${IMAGE_NS}/gabi-ingest:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd gabi-infra
            git pull
            docker compose pull
            ./scripts/deploy.sh
